# Generated by Django 5.1.4 on 2025-01-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6)),
                ('breed', models.CharField(max_length=50)),
                ('colors', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
    ]
